title: John Doe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  EngD Candidate in Process Monitoring of the Abrasive Waterjet System
  <br><br>
  AMRC, Sheffield
  <br><br>
  <a href="https://www.linkedin.com/in/danpietrow/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-NQYPFZNBBK # your Google Analytics tracking ID here
