title: Dan Pietrow # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/danpietrow/" target="_blank" >LinkedIn</a> 
  <br><br>
  EngD Candidate in Process Monitoring of the Abrasive Waterjet System
  <br><br>
  AMRC, Sheffield
  
theme: jekyll-theme-minimal
google_analytics: G-NQYPFZNBBK # your Google Analytics tracking ID here
