title: Dan Pietrow
logo: "/images/logo.jpg?raw=true" 
description: 
  <p>
  <a href="https://www.linkedin.com/in/danpietrow/" target="_blank" >LinkedIn</a> 
  </p>
  <p align="justify">
  EngD Candidate in Process Monitoring of the Abrasive Waterjet System
  <br><br>
  Sponsored by AMRC
  </p>
theme: jekyll-theme-minimal
google_analytics: G-NQYPFZNBBK # your Google Analytics tracking ID here
